### ISSUE TITLE
RESBコマンドの修正

### ISSUE THREAD

**Issue by hangingman** [hangingman/osask#10]
オペコードとしての`DB`は実装できたので、次は`RESB`を直す。
現状は使うとsegfaultになる。

**Comment by Hiroyuki-Nagata** [comment]
* とりあえずsegfaultにはならなくなったが、必要なバイナリが吐かれない。

**Comment by Hiroyuki-Nagata** [comment]
http://stackoverflow.com/a/34269437/2565527

**Comment by Hiroyuki-Nagata** [comment]
だんだん原因がわかってきた。`union`を使った際の表記に由来するバグ。

* 共用体を定義して使い回す作戦

  * [Converting an int into a 4 byte char array (C)](http://stackoverflow.com/questions/3784263/converting-an-int-into-a-4-byte-char-array-c)
```
typedef union {
	UINT integer;
	UCHAR byte[4];
} nask32bitInt;

---

// 宣言（基本はunsigned charのポインタとして使用）
nask32bitInt* bp; // 元コード： UCHAR* bp;

// 添字アクセス
bp->byte[0] = 0x00; // 元コード： bp[0] = 0x00;

// クソインクリメント表記（多分こういう意味）
bp->byte[1] = 0xe7; // 元コード： *bp++ = 0xe7;
```

これらに加えて、

* `bp`の示す4バイトを超えるアクセスをする際は以下のサイトを見る
[配列に間接参照する](http://wisdom.sakura.ne.jp/programming/c/c22.html)

```
// 現在のbpから１要素インクリメントしたbpへの添字アクセス
(bp[1]).byte[2] = 0x30 | itp->param[1];
```

**Comment by Hiroyuki-Nagata** [comment]
上記のunionはインクリメントすると4byte移動する
[wandbox](http://melpon.org/wandbox/permlink/F2hoAaIZjkxwbkXS)

**Comment by Hiroyuki-Nagata** [comment]
`put_expr`関数がちゃんと呼べない問題発生

**Comment by Hiroyuki-Nagata** [comment]
以下でsegfault
[ll.cpp:1242](https://github.com/Hiroyuki-Nagata/osask/blob/master/20GO/libnask/ll.cpp#L1242)

```
		if (c == 0x59) {
			/* TIMES */
			LOG_DEBUG("TIMES microcode");
			t = s;
			i = s[0] | s[1] << 8 | s[2] << 16 | s[3] << 24;
			s += 4;
			calc_value(value, &s); /* len */  <---- ここでsegfault
			/* lenにエラーはないという前提(プログラムカウンタを含まない定数式) */
			if ((unsigned int) i < 0xfffffff0) {
				min += (i - 1) * value->min; /* iは繰り返し回数 */
				s = skip_expr(s);
				continue;
			}
```

**Comment by Hiroyuki-Nagata** [comment]
ここで `s` には読み込んだ情報が入るはずだが入らない。これをクリアすれば一応行けるはずだが…

libnask.cpp:2316
```
	       if (c == 0x59) {
		    /* TIMES microcode */
		    dest0[0] = 0x59;
		    s = ifdef->expr[8];
		    k = ifdef->dat[8];
```

**Comment by Hiroyuki-Nagata** [comment]
* [ll.cpp:1034](https://github.com/Hiroyuki-Nagata/osask/blob/fix_resb_command_ll/20GO/libnask/ll.cpp#L1034)

* `0x59`が指定されたあとは、次の４バイトにTIMESの回数が書いていてほしいのに、実行時にログを出すと入っていない…ポインタはクソ

  * それ故に`calc_value(value, &src0);`にて、演算が失敗する
  * そこが失敗しなければ`times_count = value->min;`にて`times_count`が満たされるはず

```
# 理想
0x59, 0x00, 0x00, 0x00, 0x10
# 現実
0x59, 0x00, 0x00, 0x00, 0x00
```

```
			if (c == 0x59) {
				/* TIMES */
				times_dest0 = dest0;
				times_src0 = src0;
				src0 += 4;
				calc_value(value, &src0); /* len */
				/* lenの部分にエラーはないということになっている(手抜き) */
				times_count = value->min;
				src0 = skip_expr(src0);

		     		LOG_DEBUG("TIMES microcode \nvalue: %s \ntimes_count: %d \n",
					  value->to_string().c_str(), times_count);
				continue;
			}
```

**Comment by Hiroyuki-Nagata** [comment]
参考用としてリポジトリにかつてのosaskのソースを置いてみた
naskが登場するのは [このコミットから](https://github.com/Hiroyuki-Nagata/osask/commit/795a8d2360f7c6a856ef374b730ad7f1869ea007)

Linuxでwineを使った状態ならば、naskが動作することも確認できた

* このまま修正を続行するか、それともwineみたいにnaskを再実装したほうがはやいかもしれない。

**Comment by hangingman** [comment]
osaskの元ソースを修正するのは諦めたので、以下でやった
https://github.com/HobbyOSs/opennask
